[package]
name = "job-boardwalk-desktop-manager"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
slint.workspace = true
ureq.workspace = true

[build-dependencies]
slint-build.workspace = true

[lints]
workspace = true
